### ISSUE TITLE
Controllare che tutti i metodi di DSLEngine siano validi

### ISSUE THREAD

**Issue by ButlerBusters** [BugBusterSWE/DSLEngine#2]
Activity: #1 

Oltre a verificare che ogni metodo sia valido, bisognerà controllare che i metodi di MaaP invocati siano corretti con la versione attuale di mongoose. DSLEngine usa i modelli in src/model.

Link task: [https://bugbusters.teamwork.com/tasks/6766197](https://bugbusters.teamwork.com/tasks/6766197)

**Comment by korut94** [comment]
Controllo sostituito con i test presi da MaaP.
