### ISSUE TITLE
Metodi da testare

### ISSUE THREAD

**Issue by korut94** [BugBusterSWE/DSLEngine#7]
Modifiche apportate:

| DslDomain | metodo | modifica |
| --- | --- | --- |
|  | getErrors | Eliminato |
|  | registerCollection | Rinominato in register |
|  | loadDSL | Ritorna una Promise con un array di id di stringhe, altrimenti un MaapError |

Elenti individuati:

**registerCollection() TU-14** _test/model/DslDomain.js_  `L.152`
- [ ] Aggiunge una collection al registro
- [ ] Gestisce il caso in cui la collection sia già presente nel modelRegistry

**getCollectionModel() TU-15** _test/model/DslDomain.js_  `L.230`
- [ ] Restituisce la collection con l'id dato

**getErrors() TU-16** _test/model/DslDomain.js_  `L.247`
- [ ] Restituisce l'array di errori

**Comment by Polpetta** [comment]
non riesco a capire le modifiche apportate a loadDSL

Non vedo dove la roba viene ritornata

**Comment by Polpetta** [comment]
`registerCollection` è stato rinominato? Cercando nel codice sembra di no

**Comment by korut94** [comment]
E' tutto nel branch enhanced.

**Comment by Polpetta** [comment]
Pensavo si usasse il classico Workflow delle norme.
Il 30 mag 2016 10:00, "Andrea Mantovani" notifications@github.com ha
scritto:

**Comment by korut94** [comment]
Finche lavoro io con l'unica cosa da fare mi apro branch quando mi servono.

**Comment by Polpetta** [comment]
Chiudo in quando obsoleta
